### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode

### ISSUE THREAD

**Issue by darkyng** [Pasanlaksitha/Shazam-Downloader#1]
here's a bunch of errors when i launch the script
![image](https://user-images.githubusercontent.com/86430514/234115220-17f62021-dfd9-43cf-93d5-9eadb97b8661.png)

**Comment by Pasanlaksitha** [comment]
The problem has been resolved in the most recent commit, sorry for the delayed response.


[ Reference (stackoverflow) ](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character)

[fixed issue] (https://github.com/Pasanlaksitha/Shazam-Downloader/commit/58da88c3e0ce5ce04d8978c2b8f400520e50401c)
